<?php

class SourceAData
{
    static function get():array {
        $dataSourceXml = simplexml_load_string(self::data());

        $tempDataArray =  json_decode(json_encode($dataSourceXml), true);
        // TODO: Add safety check
        return $tempDataArray['Contacts']['Contact'];
    }

    static function data() {
        return <<<XML
            <Response xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
              <Id>90236254-f7b6-460d-9b51-88bd9757c342</Id>
              <Status>OK</Status>
              <ProviderName>Data API Previewer</ProviderName>
              <DateTimeUTC>2011-04-26T10:12:38.7756044Z</DateTimeUTC>
              <Contacts>
                <Contact>
                  <ContactID>4acf731f-af81-4ed3-96b2-0c408b2d98c0</ContactID>
                  <ContactStatus>ACTIVE</ContactStatus>
                  <Name>Carlton Functions</Name>
                  <Addresses>
                    <Address>
                      <AddressType>STREET</AddressType>
                    </Address>
                    <Address>
                      <AddressType>POBOX</AddressType>
                    </Address>
                  </Addresses>
                  <Phones>
                    <Phone>
                      <PhoneType>FAX</PhoneType>
                    </Phone>
                    <Phone>
                      <PhoneType>DEFAULT</PhoneType>
                      <PhoneNumber>9179945</PhoneNumber>
                      <PhoneAreaCode>02</PhoneAreaCode>
                    </Phone>
                    <Phone>
                      <PhoneType>MOBILE</PhoneType>
                    </Phone>
                    <Phone>
                      <PhoneType>DDI</PhoneType>
                    </Phone>
                  </Phones>
                  <UpdatedDateUTC>2011-04-21T20:49:22.267</UpdatedDateUTC>
                  <IsSupplier>true</IsSupplier>
                  <IsCustomer>false</IsCustomer>
                </Contact>
                <Contact>
                  <ContactID>adf801de-a142-4670-906f-0d46c5d7c693</ContactID>
                  <ContactStatus>ACTIVE</ContactStatus>
                  <Name>Gable Print</Name>
                  <Addresses>
                    <Address>
                      <AddressType>POBOX</AddressType>
                    </Address>
                    <Address>
                      <AddressType>STREET</AddressType>
                    </Address>
                  </Addresses>
                  <Phones>
                    <Phone>
                      <PhoneType>FAX</PhoneType>
                    </Phone>
                    <Phone>
                      <PhoneType>MOBILE</PhoneType>
                    </Phone>
                    <Phone>
                      <PhoneType>DEFAULT</PhoneType>
                    </Phone>
                    <Phone>
                      <PhoneType>DDI</PhoneType>
                    </Phone>
                  </Phones>
                  <UpdatedDateUTC>2011-04-11T02:26:12.467</UpdatedDateUTC>
                  <IsSupplier>false</IsSupplier>
                  <IsCustomer>false</IsCustomer>
                </Contact>
                <Contact>
                  <ContactID>74ea95ea-6e1e-435d-9c30-0dff8ae1bd80</ContactID>
                  <ContactStatus>ACTIVE</ContactStatus>
                  <Name>Office Supplies Company</Name>
                  <Addresses>
                    <Address>
                      <AddressType>POBOX</AddressType>
                    </Address>
                    <Address>
                      <AddressType>STREET</AddressType>
                    </Address>
                  </Addresses>
                  <Phones>
                    <Phone>
                      <PhoneType>DEFAULT</PhoneType>
                    </Phone>
                    <Phone>
                      <PhoneType>FAX</PhoneType>
                    </Phone>
                    <Phone>
                      <PhoneType>DDI</PhoneType>
                    </Phone>
                    <Phone>
                      <PhoneType>MOBILE</PhoneType>
                    </Phone>
                  </Phones>
                  <UpdatedDateUTC>2011-04-11T02:26:12.653</UpdatedDateUTC>
                  <IsSupplier>false</IsSupplier>
                  <IsCustomer>false</IsCustomer>
                </Contact>
                <Contact>
                  <ContactID>f5a77e82-50e3-4340-a6e0-13d6a482a08a</ContactID>
                  <ContactStatus>ACTIVE</ContactStatus>
                  <Name>SMART Agency</Name>
                  <Addresses>
                    <Address>
                      <AddressType>POBOX</AddressType>
                    </Address>
                    <Address>
                      <AddressType>STREET</AddressType>
                    </Address>
                  </Addresses>
                  <Phones>
                    <Phone>
                      <PhoneType>DEFAULT</PhoneType>
                      <PhoneNumber>9159889</PhoneNumber>
                      <PhoneAreaCode>02</PhoneAreaCode>
                    </Phone>
                    <Phone>
                      <PhoneType>DDI</PhoneType>
                    </Phone>
                    <Phone>
                      <PhoneType>FAX</PhoneType>
                    </Phone>
                    <Phone>
                      <PhoneType>MOBILE</PhoneType>
                    </Phone>
                  </Phones>
                  <UpdatedDateUTC>2011-04-21T20:49:22.173</UpdatedDateUTC>
                  <IsSupplier>true</IsSupplier>
                  <IsCustomer>false</IsCustomer>
                </Contact>
                <Contact>
                  <ContactID>bc446de5-971e-48b5-8efd-1745149844ef</ContactID>
                  <ContactStatus>ACTIVE</ContactStatus>
                  <Name>Wilson Periodicals</Name>
                  <Addresses>
                    <Address>
                      <AddressType>STREET</AddressType>
                    </Address>
                    <Address>
                      <AddressType>POBOX</AddressType>
                    </Address>
                  </Addresses>
                  <Phones>
                    <Phone>
                      <PhoneType>DEFAULT</PhoneType>
                    </Phone>
                    <Phone>
                      <PhoneType>MOBILE</PhoneType>
                    </Phone>
                    <Phone>
                      <PhoneType>DDI</PhoneType>
                    </Phone>
                    <Phone>
                      <PhoneType>FAX</PhoneType>
                    </Phone>
                  </Phones>
                  <UpdatedDateUTC>2011-04-26T00:43:38.56</UpdatedDateUTC>
                  <IsSupplier>false</IsSupplier>
                  <IsCustomer>false</IsCustomer>
                  <DefaultCurrency>GBP</DefaultCurrency>
                </Contact>
                <Contact>
                  <ContactID>aca6e01a-1815-474c-bd0f-18adfd95cfcb</ContactID>
                  <ContactStatus>ACTIVE</ContactStatus>
                  <Name>Truxton Property Management</Name>
                  <Addresses>
                    <Address>
                      <AddressType>POBOX</AddressType>
                    </Address>
                    <Address>
                      <AddressType>STREET</AddressType>
                    </Address>
                  </Addresses>
                  <Phones>
                    <Phone>
                      <PhoneType>FAX</PhoneType>
                    </Phone>
                    <Phone>
                      <PhoneType>MOBILE</PhoneType>
                    </Phone>
                    <Phone>
                      <PhoneType>DDI</PhoneType>
                    </Phone>
                    <Phone>
                      <PhoneType>DEFAULT</PhoneType>
                      <PhoneNumber>9157357</PhoneNumber>
                      <PhoneAreaCode>02</PhoneAreaCode>
                    </Phone>
                  </Phones>
                  <UpdatedDateUTC>2011-04-11T02:26:12.793</UpdatedDateUTC>
                  <IsSupplier>true</IsSupplier>
                  <IsCustomer>false</IsCustomer>
                </Contact>
                <Contact>
                  <ContactID>af0091a9-82ef-4cac-9fd6-22c095ac6a58</ContactID>
                  <ContactStatus>ACTIVE</ContactStatus>
                  <Name>Hamilton Smith Ltd</Name>
                  <EmailAddress>info@hsg.co</EmailAddress>
                  <Addresses>
                    <Address>
                      <AddressType>STREET</AddressType>
                    </Address>
                    <Address>
                      <AddressType>POBOX</AddressType>
                      <AddressLine1>3 Park Street Industrial Village</AddressLine1>
                      <City>Oaktown</City>
                      <PostalCode>OK13 3TN</PostalCode>
                    </Address>
                  </Addresses>
                  <Phones>
                    <Phone>
                      <PhoneType>MOBILE</PhoneType>
                    </Phone>
                    <Phone>
                      <PhoneType>DDI</PhoneType>
                    </Phone>
                    <Phone>
                      <PhoneType>DEFAULT</PhoneType>
                      <PhoneNumber>2345678</PhoneNumber>
                      <PhoneAreaCode>01</PhoneAreaCode>
                    </Phone>
                    <Phone>
                      <PhoneType>FAX</PhoneType>
                    </Phone>
                  </Phones>
                  <UpdatedDateUTC>2011-04-22T03:06:36.697</UpdatedDateUTC>
                  <IsSupplier>false</IsSupplier>
                  <IsCustomer>true</IsCustomer>
                </Contact>
                <Contact>
                  <ContactID>cf8fa320-a527-496c-823e-22dd069d29e6</ContactID>
                  <ContactStatus>ACTIVE</ContactStatus>
                  <Name>PC Complete</Name>
                  <Addresses>
                    <Address>
                      <AddressType>POBOX</AddressType>
                    </Address>
                    <Address>
                      <AddressType>STREET</AddressType>
                    </Address>
                  </Addresses>
                  <Phones>
                    <Phone>
                      <PhoneType>MOBILE</PhoneType>
                    </Phone>
                    <Phone>
                      <PhoneType>FAX</PhoneType>
                    </Phone>
                    <Phone>
                      <PhoneType>DDI</PhoneType>
                    </Phone>
                    <Phone>
                      <PhoneType>DEFAULT</PhoneType>
                      <PhoneNumber>322600</PhoneNumber>
                      <PhoneAreaCode>800</PhoneAreaCode>
                    </Phone>
                  </Phones>
                  <UpdatedDateUTC>2011-04-21T20:49:22.187</UpdatedDateUTC>
                  <IsSupplier>true</IsSupplier>
                  <IsCustomer>false</IsCustomer>
                </Contact>
                <Contact>
                  <ContactID>362819c9-f285-4d09-ac95-26327863adac</ContactID>
                  <ContactStatus>ACTIVE</ContactStatus>
                  <Name>Bayside Club</Name>
                  <FirstName>Bob</FirstName>
                  <LastName>Partridge</LastName>
                  <EmailAddress>bob.partridge@bayclub.co</EmailAddress>
                  <SkypeUserName>bayside577</SkypeUserName>
                  <BankAccountDetails>10-20-30 987654321</BankAccountDetails>
                  <TaxNumber>GB 234567890</TaxNumber>
                  <AccountsReceivableTaxType>OUTPUT2</AccountsReceivableTaxType>
                  <AccountsPayableTaxType>OUTPUT2</AccountsPayableTaxType>
                  <Addresses>
                    <Address>
                      <AddressType>POBOX</AddressType>
                      <AddressLine1>P O Box 3354</AddressLine1>
                      <AddressLine2>South Mailing Centre</AddressLine2>
                      <City>Oaktown</City>
                      <Region>Madeupville</Region>
                      <PostalCode>MA12 VL3</PostalCode>
                      <Country>United Kingdom</Country>
                      <AttentionTo>Club Secretary</AttentionTo>
                    </Address>
                    <Address>
                      <AddressType>STREET</AddressType>
                      <AddressLine1>148 Bay Harbour Road</AddressLine1>
                      <City>Ridge Heights</City>
                      <Region>Madeupville</Region>
                      <PostalCode>MA12 VL9</PostalCode>
                      <Country>United Kingdom</Country>
                      <AttentionTo>Club Secretary</AttentionTo>
                    </Address>
                  </Addresses>
                  <Phones>
                    <Phone>
                      <PhoneType>FAX</PhoneType>
                      <PhoneNumber>2025566</PhoneNumber>
                      <PhoneAreaCode>02</PhoneAreaCode>
                    </Phone>
                    <Phone>
                      <PhoneType>DDI</PhoneType>
                      <PhoneNumber>2024418</PhoneNumber>
                      <PhoneAreaCode>02</PhoneAreaCode>
                    </Phone>
                    <Phone>
                      <PhoneType>DEFAULT</PhoneType>
                      <PhoneNumber>2024455</PhoneNumber>
                      <PhoneAreaCode>02</PhoneAreaCode>
                    </Phone>
                    <Phone>
                      <PhoneType>MOBILE</PhoneType>
                      <PhoneNumber>7774455</PhoneNumber>
                      <PhoneAreaCode>01</PhoneAreaCode>
                    </Phone>
                  </Phones>
                  <UpdatedDateUTC>2011-04-22T03:37:20.37</UpdatedDateUTC>
                  <IsSupplier>false</IsSupplier>
                  <IsCustomer>true</IsCustomer>
                </Contact>
                <Contact>
                  <ContactID>289373e2-745c-4743-8b58-3008351f83dd</ContactID>
                  <ContactStatus>ACTIVE</ContactStatus>
                  <Name>Fulton Airport Parking</Name>
                  <Addresses>
                    <Address>
                      <AddressType>POBOX</AddressType>
                    </Address>
                    <Address>
                      <AddressType>STREET</AddressType>
                    </Address>
                  </Addresses>
                  <Phones>
                    <Phone>
                      <PhoneType>DDI</PhoneType>
                    </Phone>
                    <Phone>
                      <PhoneType>MOBILE</PhoneType>
                    </Phone>
                    <Phone>
                      <PhoneType>FAX</PhoneType>
                    </Phone>
                    <Phone>
                      <PhoneType>DEFAULT</PhoneType>
                    </Phone>
                  </Phones>
                  <UpdatedDateUTC>2011-04-11T02:26:12.437</UpdatedDateUTC>
                  <IsSupplier>false</IsSupplier>
                  <IsCustomer>false</IsCustomer>
                </Contact>
                <Contact>
                  <ContactID>3a0d40a2-2698-4cf5-b7b2-30133c632ab6</ContactID>
                  <ContactStatus>ACTIVE</ContactStatus>
                  <Name>Swanston Security</Name>
                  <Addresses>
                    <Address>
                      <AddressType>POBOX</AddressType>
                    </Address>
                    <Address>
                      <AddressType>STREET</AddressType>
                    </Address>
                  </Addresses>
                  <Phones>
                    <Phone>
                      <PhoneType>MOBILE</PhoneType>
                    </Phone>
                    <Phone>
                      <PhoneType>FAX</PhoneType>
                    </Phone>
                    <Phone>
                      <PhoneType>DDI</PhoneType>
                    </Phone>
                    <Phone>
                      <PhoneType>DEFAULT</PhoneType>
                      <PhoneNumber>112113</PhoneNumber>
                      <PhoneAreaCode>800</PhoneAreaCode>
                    </Phone>
                  </Phones>
                  <UpdatedDateUTC>2011-04-11T02:26:12.793</UpdatedDateUTC>
                  <IsSupplier>true</IsSupplier>
                  <IsCustomer>false</IsCustomer>
                </Contact>
                <Contact>
                  <ContactID>c523e12f-8b74-4d3a-bbd8-32d7a2f598b4</ContactID>
                  <ContactStatus>ACTIVE</ContactStatus>
                  <Name>City Limousines</Name>
                  <FirstName>Martin</FirstName>
                  <LastName>Dale</LastName>
                  <EmailAddress>martyd@citylim.co</EmailAddress>
                  <Addresses>
                    <Address>
                      <AddressType>STREET</AddressType>
                    </Address>
                    <Address>
                      <AddressType>POBOX</AddressType>
                      <AddressLine1>1206 Harbour Tower</AddressLine1>
                      <AddressLine2>59-65 South Street</AddressLine2>
                      <City>Coppertown</City>
                      <PostalCode>CP89 TN4</PostalCode>
                      <AttentionTo>Accounts Dept</AttentionTo>
                    </Address>
                  </Addresses>
                  <Phones>
                    <Phone>
                      <PhoneType>MOBILE</PhoneType>
                      <PhoneNumber>7774001</PhoneNumber>
                      <PhoneAreaCode>01</PhoneAreaCode>
                    </Phone>
                    <Phone>
                      <PhoneType>FAX</PhoneType>
                    </Phone>
                    <Phone>
                      <PhoneType>DDI</PhoneType>
                    </Phone>
                    <Phone>
                      <PhoneType>DEFAULT</PhoneType>
                      <PhoneNumber>8004001</PhoneNumber>
                      <PhoneAreaCode>01</PhoneAreaCode>
                    </Phone>
                  </Phones>
                  <UpdatedDateUTC>2011-04-22T03:37:20.133</UpdatedDateUTC>
                  <IsSupplier>false</IsSupplier>
                  <IsCustomer>true</IsCustomer>
                </Contact>
                <Contact>
                  <ContactID>5a83dcee-ee21-4ee8-b53b-381b93346256</ContactID>
                  <ContactStatus>ACTIVE</ContactStatus>
                  <Name>Brunswick Petals</Name>
                  <Addresses>
                    <Address>
                      <AddressType>STREET</AddressType>
                    </Address>
                    <Address>
                      <AddressType>POBOX</AddressType>
                    </Address>
                  </Addresses>
                  <Phones>
                    <Phone>
                      <PhoneType>DDI</PhoneType>
                    </Phone>
                    <Phone>
                      <PhoneType>MOBILE</PhoneType>
                    </Phone>
                    <Phone>
                      <PhoneType>FAX</PhoneType>
                    </Phone>
                    <Phone>
                      <PhoneType>DEFAULT</PhoneType>
                    </Phone>
                  </Phones>
                  <UpdatedDateUTC>2011-04-11T02:26:12.263</UpdatedDateUTC>
                  <IsSupplier>false</IsSupplier>
                  <IsCustomer>false</IsCustomer>
                </Contact>
                <Contact>
                  <ContactID>a852a44c-3d8f-4c4b-a628-3a2c2121b9b1</ContactID>
                  <ContactStatus>ACTIVE</ContactStatus>
                  <Name>Bank West</Name>
                  <Addresses>
                    <Address>
                      <AddressType>POBOX</AddressType>
                      <AddressLine1>Procurement Services</AddressLine1>
                      <AddressLine2>GPO 1234</AddressLine2>
                      <City>Pinehaven</City>
                      <PostalCode>PI98 7HV</PostalCode>
                    </Address>
                    <Address>
                      <AddressType>STREET</AddressType>
                    </Address>
                  </Addresses>
                  <Phones>
                    <Phone>
                      <PhoneType>MOBILE</PhoneType>
                    </Phone>
                    <Phone>
                      <PhoneType>DEFAULT</PhoneType>
                      <PhoneNumber>2023456</PhoneNumber>
                      <PhoneAreaCode>02</PhoneAreaCode>
                    </Phone>
                    <Phone>
                      <PhoneType>FAX</PhoneType>
                    </Phone>
                    <Phone>
                      <PhoneType>DDI</PhoneType>
                    </Phone>
                  </Phones>
                  <UpdatedDateUTC>2011-04-21T04:24:12.347</UpdatedDateUTC>
                  <IsSupplier>false</IsSupplier>
                  <IsCustomer>true</IsCustomer>
                </Contact>
                <Contact>
                  <ContactID>737982b0-2811-44c9-bdb3-3b26a3a6ef8c</ContactID>
                  <ContactStatus>ACTIVE</ContactStatus>
                  <Name>Ridgeway Bank</Name>
                  <Addresses>
                    <Address>
                      <AddressType>STREET</AddressType>
                    </Address>
                    <Address>
                      <AddressType>POBOX</AddressType>
                    </Address>
                  </Addresses>
                  <Phones>
                    <Phone>
                      <PhoneType>DDI</PhoneType>
                    </Phone>
                    <Phone>
                      <PhoneType>DEFAULT</PhoneType>
                    </Phone>
                    <Phone>
                      <PhoneType>FAX</PhoneType>
                    </Phone>
                    <Phone>
                      <PhoneType>MOBILE</PhoneType>
                    </Phone>
                  </Phones>
                  <UpdatedDateUTC>2011-04-11T02:26:12.747</UpdatedDateUTC>
                  <IsSupplier>false</IsSupplier>
                  <IsCustomer>false</IsCustomer>
                </Contact>
                <Contact>
                  <ContactID>8a593982-291c-4ec3-9a42-3dbccbc6e3c8</ContactID>
                  <ContactStatus>ACTIVE</ContactStatus>
                  <Name>MCO Cleaning Services</Name>
                  <Addresses>
                    <Address>
                      <AddressType>POBOX</AddressType>
                    </Address>
                    <Address>
                      <AddressType>STREET</AddressType>
                    </Address>
                  </Addresses>
                  <Phones>
                    <Phone>
                      <PhoneType>FAX</PhoneType>
                    </Phone>
                    <Phone>
                      <PhoneType>MOBILE</PhoneType>
                    </Phone>
                    <Phone>
                      <PhoneType>DEFAULT</PhoneType>
                      <PhoneNumber>5119119</PhoneNumber>
                      <PhoneAreaCode>02</PhoneAreaCode>
                    </Phone>
                    <Phone>
                      <PhoneType>DDI</PhoneType>
                    </Phone>
                  </Phones>
                  <UpdatedDateUTC>2011-04-21T20:49:22.11</UpdatedDateUTC>
                  <IsSupplier>true</IsSupplier>
                  <IsCustomer>false</IsCustomer>
                </Contact>
                <Contact>
                  <ContactID>7eccc5ab-cee8-4af4-b2a9-3f9b17f03095</ContactID>
                  <ContactStatus>ACTIVE</ContactStatus>
                  <Name>Petrie McLoud Watson &amp; Associates</Name>
                  <FirstName>Morris</FirstName>
                  <LastName>McKenzie</LastName>
                  <EmailAddress>mm@pmwla.co</EmailAddress>
                  <Addresses>
                    <Address>
                      <AddressType>POBOX</AddressType>
                      <AddressLine1>9 Branyard Terrace</AddressLine1>
                      <City>Coppertown</City>
                      <PostalCode>CP89 TN3</PostalCode>
                    </Address>
                    <Address>
                      <AddressType>STREET</AddressType>
                    </Address>
                  </Addresses>
                  <Phones>
                    <Phone>
                      <PhoneType>DDI</PhoneType>
                    </Phone>
                    <Phone>
                      <PhoneType>FAX</PhoneType>
                    </Phone>
                    <Phone>
                      <PhoneType>DEFAULT</PhoneType>
                      <PhoneNumber>4561</PhoneNumber>
                      <PhoneAreaCode>915</PhoneAreaCode>
                      <PhoneCountryCode>02</PhoneCountryCode>
                    </Phone>
                    <Phone>
                      <PhoneType>MOBILE</PhoneType>
                    </Phone>
                  </Phones>
                  <UpdatedDateUTC>2011-04-21T04:24:12.253</UpdatedDateUTC>
                  <IsSupplier>false</IsSupplier>
                  <IsCustomer>true</IsCustomer>
                </Contact>
                <Contact>
                  <ContactID>699f0091-b127-4796-9f15-41a2f42abeb2</ContactID>
                  <ContactStatus>ACTIVE</ContactStatus>
                  <Name>ABC Furniture</Name>
                  <FirstName>Trish</FirstName>
                  <LastName>Rawlings</LastName>
                  <EmailAddress>info@abfl.com</EmailAddress>
                  <Addresses>
                    <Address>
                      <AddressType>POBOX</AddressType>
                    </Address>
                    <Address>
                      <AddressType>STREET</AddressType>
                    </Address>
                  </Addresses>
                  <Phones>
                    <Phone>
                      <PhoneType>MOBILE</PhoneType>
                    </Phone>
                    <Phone>
                      <PhoneType>DDI</PhoneType>
                    </Phone>
                    <Phone>
                      <PhoneType>FAX</PhoneType>
                    </Phone>
                    <Phone>
                      <PhoneType>DEFAULT</PhoneType>
                      <PhoneNumber>124578</PhoneNumber>
                      <PhoneAreaCode>800</PhoneAreaCode>
                    </Phone>
                  </Phones>
                  <UpdatedDateUTC>2011-04-21T20:49:22.327</UpdatedDateUTC>
                  <IsSupplier>true</IsSupplier>
                  <IsCustomer>false</IsCustomer>
                </Contact>
                <Contact>
                  <ContactID>1262c350-fe0f-40ec-aeff-41c95b4a45af</ContactID>
                  <ContactStatus>ACTIVE</ContactStatus>
                  <Name>DIISR - Small Business Services</Name>
                  <EmailAddress>cad@diisr.govt</EmailAddress>
                  <SkypeUserName>maggie-diisr</SkypeUserName>
                  <Addresses>
                    <Address>
                      <AddressType>POBOX</AddressType>
                      <AddressLine1>GPO 9566</AddressLine1>
                      <City>Pinehaven</City>
                      <PostalCode>PI98 2HV</PostalCode>
                      <AttentionTo>Corporate Accounting</AttentionTo>
                    </Address>
                    <Address>
                      <AddressType>STREET</AddressType>
                    </Address>
                  </Addresses>
                  <Phones>
                    <Phone>
                      <PhoneType>DEFAULT</PhoneType>
                      <PhoneNumber>8009001</PhoneNumber>
                      <PhoneAreaCode>01</PhoneAreaCode>
                    </Phone>
                    <Phone>
                      <PhoneType>FAX</PhoneType>
                      <PhoneNumber>8009002</PhoneNumber>
                      <PhoneAreaCode>01</PhoneAreaCode>
                    </Phone>
                    <Phone>
                      <PhoneType>DDI</PhoneType>
                    </Phone>
                    <Phone>
                      <PhoneType>MOBILE</PhoneType>
                    </Phone>
                  </Phones>
                  <UpdatedDateUTC>2011-04-22T03:06:37.057</UpdatedDateUTC>
                  <IsSupplier>false</IsSupplier>
                  <IsCustomer>true</IsCustomer>
                </Contact>
                <Contact>
                  <ContactID>f559658a-68da-42b1-81ae-42a96b6c6953</ContactID>
                  <ContactStatus>ACTIVE</ContactStatus>
                  <Name>Gateway Motors</Name>
                  <Addresses>
                    <Address>
                      <AddressType>STREET</AddressType>
                    </Address>
                    <Address>
                      <AddressType>POBOX</AddressType>
                    </Address>
                  </Addresses>
                  <Phones>
                    <Phone>
                      <PhoneType>MOBILE</PhoneType>
                    </Phone>
                    <Phone>
                      <PhoneType>DDI</PhoneType>
                    </Phone>
                    <Phone>
                      <PhoneType>FAX</PhoneType>
                    </Phone>
                    <Phone>
                      <PhoneType>DEFAULT</PhoneType>
                      <PhoneNumber>349227</PhoneNumber>
                      <PhoneAreaCode>800</PhoneAreaCode>
                    </Phone>
                  </Phones>
                  <UpdatedDateUTC>2011-04-21T20:49:22.03</UpdatedDateUTC>
                  <IsSupplier>true</IsSupplier>
                  <IsCustomer>false</IsCustomer>
                </Contact>
                <Contact>
                  <ContactID>8894cc85-85c2-4fd2-9eb6-537179d1a12d</ContactID>
                  <ContactStatus>ACTIVE</ContactStatus>
                  <Name>Hoyt Productions</Name>
                  <Addresses>
                    <Address>
                      <AddressType>STREET</AddressType>
                    </Address>
                    <Address>
                      <AddressType>POBOX</AddressType>
                    </Address>
                  </Addresses>
                  <Phones>
                    <Phone>
                      <PhoneType>DDI</PhoneType>
                    </Phone>
                    <Phone>
                      <PhoneType>DEFAULT</PhoneType>
                      <PhoneNumber>7411234</PhoneNumber>
                      <PhoneAreaCode>02</PhoneAreaCode>
                    </Phone>
                    <Phone>
                      <PhoneType>FAX</PhoneType>
                    </Phone>
                    <Phone>
                      <PhoneType>MOBILE</PhoneType>
                    </Phone>
                  </Phones>
                  <UpdatedDateUTC>2011-04-21T20:49:22.233</UpdatedDateUTC>
                  <IsSupplier>true</IsSupplier>
                  <IsCustomer>false</IsCustomer>
                </Contact>
                <Contact>
                  <ContactID>847933f0-7c35-4e5b-b884-5f9df64c8e4b</ContactID>
                  <ContactStatus>ACTIVE</ContactStatus>
                  <Name>Port &amp; Philip Freight</Name>
                  <Addresses>
                    <Address>
                      <AddressType>STREET</AddressType>
                    </Address>
                    <Address>
                      <AddressType>POBOX</AddressType>
                      <AddressLine1>900 Harbourside Drive</AddressLine1>
                      <City>Oaktown</City>
                      <PostalCode>OK14 7TN</PostalCode>
                      <AttentionTo>Corporate Services</AttentionTo>
                    </Address>
                  </Addresses>
                  <Phones>
                    <Phone>
                      <PhoneType>DDI</PhoneType>
                    </Phone>
                    <Phone>
                      <PhoneType>DEFAULT</PhoneType>
                      <PhoneNumber>2323434</PhoneNumber>
                      <PhoneAreaCode>01</PhoneAreaCode>
                    </Phone>
                    <Phone>
                      <PhoneType>FAX</PhoneType>
                    </Phone>
                    <Phone>
                      <PhoneType>MOBILE</PhoneType>
                    </Phone>
                  </Phones>
                  <UpdatedDateUTC>2011-04-22T03:06:36.62</UpdatedDateUTC>
                  <IsSupplier>false</IsSupplier>
                  <IsCustomer>true</IsCustomer>
                </Contact>
                <Contact>
                  <ContactID>94a82e91-53da-4f87-a417-63d6a1607ced</ContactID>
                  <ContactStatus>ACTIVE</ContactStatus>
                  <Name>Young Bros Transport</Name>
                  <EmailAddress>rog@ybt.co</EmailAddress>
                  <Addresses>
                    <Address>
                      <AddressType>POBOX</AddressType>
                      <AddressLine1>P O Box 5678</AddressLine1>
                      <AddressLine2>Central Mailing Centre</AddressLine2>
                      <City>Oaktown</City>
                      <PostalCode>OK12 5TN</PostalCode>
                    </Address>
                    <Address>
                      <AddressType>STREET</AddressType>
                    </Address>
                  </Addresses>
                  <Phones>
                    <Phone>
                      <PhoneType>MOBILE</PhoneType>
                    </Phone>
                    <Phone>
                      <PhoneType>DDI</PhoneType>
                    </Phone>
                    <Phone>
                      <PhoneType>DEFAULT</PhoneType>
                      <PhoneNumber>3435678</PhoneNumber>
                      <PhoneAreaCode>02</PhoneAreaCode>
                    </Phone>
                    <Phone>
                      <PhoneType>FAX</PhoneType>
                    </Phone>
                  </Phones>
                  <UpdatedDateUTC>2011-04-22T03:06:36.65</UpdatedDateUTC>
                  <IsSupplier>true</IsSupplier>
                  <IsCustomer>true</IsCustomer>
                </Contact>
                <Contact>
                  <ContactID>f1c18eb1-cdc5-4f11-9867-666cbbc397fe</ContactID>
                  <ContactStatus>ACTIVE</ContactStatus>
                  <Name>Coco Cafe</Name>
                  <Addresses>
                    <Address>
                      <AddressType>STREET</AddressType>
                    </Address>
                    <Address>
                      <AddressType>POBOX</AddressType>
                    </Address>
                  </Addresses>
                  <Phones>
                    <Phone>
                      <PhoneType>MOBILE</PhoneType>
                    </Phone>
                    <Phone>
                      <PhoneType>DDI</PhoneType>
                    </Phone>
                    <Phone>
                      <PhoneType>FAX</PhoneType>
                    </Phone>
                    <Phone>
                      <PhoneType>DEFAULT</PhoneType>
                    </Phone>
                  </Phones>
                  <UpdatedDateUTC>2011-04-11T02:26:12.357</UpdatedDateUTC>
                  <IsSupplier>false</IsSupplier>
                  <IsCustomer>false</IsCustomer>
                </Contact>
                <Contact>
                  <ContactID>9ce626d2-14ea-463c-9fff-6785ab5f9bfb</ContactID>
                  <ContactStatus>ACTIVE</ContactStatus>
                  <Name>Boom FM</Name>
                  <Addresses>
                    <Address>
                      <AddressType>POBOX</AddressType>
                      <AddressLine1>P O Box 3955</AddressLine1>
                      <AddressLine2>South Mailing Centre</AddressLine2>
                      <City>Oaktown</City>
                      <PostalCode>OK12 3TN</PostalCode>
                      <AttentionTo>Human Resources Manager</AttentionTo>
                    </Address>
                    <Address>
                      <AddressType>STREET</AddressType>
                    </Address>
                  </Addresses>
                  <Phones>
                    <Phone>
                      <PhoneType>FAX</PhoneType>
                    </Phone>
                    <Phone>
                      <PhoneType>DEFAULT</PhoneType>
                      <PhoneNumber>9191</PhoneNumber>
                      <PhoneAreaCode>555</PhoneAreaCode>
                      <PhoneCountryCode>01</PhoneCountryCode>
                    </Phone>
                    <Phone>
                      <PhoneType>DDI</PhoneType>
                    </Phone>
                    <Phone>
                      <PhoneType>MOBILE</PhoneType>
                    </Phone>
                  </Phones>
                  <UpdatedDateUTC>2011-04-21T04:24:12.283</UpdatedDateUTC>
                  <IsSupplier>false</IsSupplier>
                  <IsCustomer>true</IsCustomer>
                </Contact>
                <Contact>
                  <ContactID>e4c9d0e2-c285-4e85-b579-6d28b180c730</ContactID>
                  <ContactStatus>ACTIVE</ContactStatus>
                  <Name>24 Locks</Name>
                  <Addresses>
                    <Address>
                      <AddressType>STREET</AddressType>
                    </Address>
                    <Address>
                      <AddressType>POBOX</AddressType>
                    </Address>
                  </Addresses>
                  <Phones>
                    <Phone>
                      <PhoneType>DDI</PhoneType>
                    </Phone>
                    <Phone>
                      <PhoneType>DEFAULT</PhoneType>
                    </Phone>
                    <Phone>
                      <PhoneType>MOBILE</PhoneType>
                    </Phone>
                    <Phone>
                      <PhoneType>FAX</PhoneType>
                    </Phone>
                  </Phones>
                  <UpdatedDateUTC>2011-04-11T02:26:12.093</UpdatedDateUTC>
                  <IsSupplier>false</IsSupplier>
                  <IsCustomer>false</IsCustomer>
                </Contact>
                <Contact>
                  <ContactID>b9d4332a-26a3-4577-8db2-6e830d4b07cd</ContactID>
                  <ContactStatus>ACTIVE</ContactStatus>
                  <Name>Berry Brew</Name>
                  <Addresses>
                    <Address>
                      <AddressType>STREET</AddressType>
                    </Address>
                    <Address>
                      <AddressType>POBOX</AddressType>
                    </Address>
                  </Addresses>
                  <Phones>
                    <Phone>
                      <PhoneType>DEFAULT</PhoneType>
                    </Phone>
                    <Phone>
                      <PhoneType>FAX</PhoneType>
                    </Phone>
                    <Phone>
                      <PhoneType>DDI</PhoneType>
                    </Phone>
                    <Phone>
                      <PhoneType>MOBILE</PhoneType>
                    </Phone>
                  </Phones>
                  <UpdatedDateUTC>2011-04-11T02:26:12.233</UpdatedDateUTC>
                  <IsSupplier>false</IsSupplier>
                  <IsCustomer>false</IsCustomer>
                </Contact>
                <Contact>
                  <ContactID>a871a956-05b5-4e2a-9419-7aeb478ca647</ContactID>
                  <ContactStatus>ACTIVE</ContactStatus>
                  <Name>Ridgeway University</Name>
                  <Addresses>
                    <Address>
                      <AddressType>POBOX</AddressType>
                      <AddressLine1>9-123 Lambda Ave</AddressLine1>
                      <City>Coppertown</City>
                      <PostalCode>CP89 TN2</PostalCode>
                      <AttentionTo>Accounts Dept</AttentionTo>
                    </Address>
                    <Address>
                      <AddressType>STREET</AddressType>
                    </Address>
                  </Addresses>
                  <Phones>
                    <Phone>
                      <PhoneType>DDI</PhoneType>
                    </Phone>
                    <Phone>
                      <PhoneType>MOBILE</PhoneType>
                      <PhoneNumber>7775001</PhoneNumber>
                      <PhoneAreaCode>01</PhoneAreaCode>
                    </Phone>
                    <Phone>
                      <PhoneType>DEFAULT</PhoneType>
                      <PhoneNumber>8005001</PhoneNumber>
                      <PhoneAreaCode>01</PhoneAreaCode>
                    </Phone>
                    <Phone>
                      <PhoneType>FAX</PhoneType>
                    </Phone>
                  </Phones>
                  <UpdatedDateUTC>2011-04-22T03:37:20.197</UpdatedDateUTC>
                  <IsSupplier>false</IsSupplier>
                  <IsCustomer>true</IsCustomer>
                </Contact>
                <Contact>
                  <ContactID>0b787601-82f5-438f-9fb7-7eeb0a09b2a0</ContactID>
                  <ContactStatus>ACTIVE</ContactStatus>
                  <Name>Melrose Parking</Name>
                  <Addresses>
                    <Address>
                      <AddressType>STREET</AddressType>
                    </Address>
                    <Address>
                      <AddressType>POBOX</AddressType>
                    </Address>
                  </Addresses>
                  <Phones>
                    <Phone>
                      <PhoneType>DEFAULT</PhoneType>
                    </Phone>
                    <Phone>
                      <PhoneType>DDI</PhoneType>
                    </Phone>
                    <Phone>
                      <PhoneType>MOBILE</PhoneType>
                    </Phone>
                    <Phone>
                      <PhoneType>FAX</PhoneType>
                    </Phone>
                  </Phones>
                  <UpdatedDateUTC>2011-04-11T02:26:12.607</UpdatedDateUTC>
                  <IsSupplier>false</IsSupplier>
                  <IsCustomer>false</IsCustomer>
                </Contact>
                <Contact>
                  <ContactID>dec56ceb-65e9-43b3-ac98-7fe09eb37e31</ContactID>
                  <ContactStatus>ACTIVE</ContactStatus>
                  <Name>PowerDirect</Name>
                  <BankAccountDetails>30-20-10 102030405</BankAccountDetails>
                  <Addresses>
                    <Address>
                      <AddressType>STREET</AddressType>
                    </Address>
                    <Address>
                      <AddressType>POBOX</AddressType>
                      <AddressLine1>P O Box 8900</AddressLine1>
                      <AddressLine2>Central Mailing Centre</AddressLine2>
                      <City>Oaktown</City>
                      <PostalCode>OK12 8TN</PostalCode>
                    </Address>
                  </Addresses>
                  <Phones>
                    <Phone>
                      <PhoneType>MOBILE</PhoneType>
                    </Phone>
                    <Phone>
                      <PhoneType>DDI</PhoneType>
                    </Phone>
                    <Phone>
                      <PhoneType>FAX</PhoneType>
                      <PhoneNumber>887613</PhoneNumber>
                      <PhoneAreaCode>800</PhoneAreaCode>
                    </Phone>
                    <Phone>
                      <PhoneType>DEFAULT</PhoneType>
                      <PhoneNumber>887612</PhoneNumber>
                      <PhoneAreaCode>800</PhoneAreaCode>
                    </Phone>
                  </Phones>
                  <UpdatedDateUTC>2011-04-19T00:07:36.883</UpdatedDateUTC>
                  <IsSupplier>true</IsSupplier>
                  <IsCustomer>false</IsCustomer>
                </Contact>
                <Contact>
                  <ContactID>c82900a5-064c-46e1-9d8b-86404c6bfd01</ContactID>
                  <ContactStatus>ACTIVE</ContactStatus>
                  <Name>Espresso 31</Name>
                  <Addresses>
                    <Address>
                      <AddressType>STREET</AddressType>
                    </Address>
                    <Address>
                      <AddressType>POBOX</AddressType>
                    </Address>
                  </Addresses>
                  <Phones>
                    <Phone>
                      <PhoneType>MOBILE</PhoneType>
                    </Phone>
                    <Phone>
                      <PhoneType>FAX</PhoneType>
                    </Phone>
                    <Phone>
                      <PhoneType>DDI</PhoneType>
                    </Phone>
                    <Phone>
                      <PhoneType>DEFAULT</PhoneType>
                    </Phone>
                  </Phones>
                  <UpdatedDateUTC>2011-04-11T02:26:12.403</UpdatedDateUTC>
                  <IsSupplier>false</IsSupplier>
                  <IsCustomer>false</IsCustomer>
                </Contact>
                <Contact>
                  <ContactID>bab779bc-c5fb-42cb-a888-953e8309711c</ContactID>
                  <ContactStatus>ACTIVE</ContactStatus>
                  <Name>7-Eleven</Name>
                  <Addresses>
                    <Address>
                      <AddressType>STREET</AddressType>
                    </Address>
                    <Address>
                      <AddressType>POBOX</AddressType>
                    </Address>
                  </Addresses>
                  <Phones>
                    <Phone>
                      <PhoneType>DEFAULT</PhoneType>
                    </Phone>
                    <Phone>
                      <PhoneType>MOBILE</PhoneType>
                    </Phone>
                    <Phone>
                      <PhoneType>DDI</PhoneType>
                    </Phone>
                    <Phone>
                      <PhoneType>FAX</PhoneType>
                    </Phone>
                  </Phones>
                  <UpdatedDateUTC>2011-04-11T02:26:12.11</UpdatedDateUTC>
                  <IsSupplier>false</IsSupplier>
                  <IsCustomer>false</IsCustomer>
                </Contact>
                <Contact>
                  <ContactID>3828f379-afa5-4b2a-9000-9c53d75ba1c6</ContactID>
                  <ContactStatus>ACTIVE</ContactStatus>
                  <Name>Central Copiers</Name>
                  <Addresses>
                    <Address>
                      <AddressType>STREET</AddressType>
                    </Address>
                    <Address>
                      <AddressType>POBOX</AddressType>
                    </Address>
                  </Addresses>
                  <Phones>
                    <Phone>
                      <PhoneType>DEFAULT</PhoneType>
                      <PhoneNumber>244844</PhoneNumber>
                      <PhoneAreaCode>800</PhoneAreaCode>
                    </Phone>
                    <Phone>
                      <PhoneType>MOBILE</PhoneType>
                    </Phone>
                    <Phone>
                      <PhoneType>FAX</PhoneType>
                    </Phone>
                    <Phone>
                      <PhoneType>DDI</PhoneType>
                    </Phone>
                  </Phones>
                  <UpdatedDateUTC>2011-04-21T20:49:22.077</UpdatedDateUTC>
                  <IsSupplier>true</IsSupplier>
                  <IsCustomer>false</IsCustomer>
                </Contact>
                <Contact>
                  <ContactID>ac48c67d-3eea-44eb-96b1-9f7a89d9b761</ContactID>
                  <ContactStatus>ACTIVE</ContactStatus>
                  <Name>Data</Name>
                  <Addresses>
                    <Address>
                      <AddressType>STREET</AddressType>
                    </Address>
                    <Address>
                      <AddressType>POBOX</AddressType>
                    </Address>
                  </Addresses>
                  <Phones>
                    <Phone>
                      <PhoneType>MOBILE</PhoneType>
                    </Phone>
                    <Phone>
                      <PhoneType>DEFAULT</PhoneType>
                      <PhoneNumber>9376</PhoneNumber>
                      <PhoneAreaCode>438</PhoneAreaCode>
                      <PhoneCountryCode>0800</PhoneCountryCode>
                    </Phone>
                    <Phone>
                      <PhoneType>DDI</PhoneType>
                    </Phone>
                    <Phone>
                      <PhoneType>FAX</PhoneType>
                    </Phone>
                  </Phones>
                  <UpdatedDateUTC>2011-04-11T02:26:12.827</UpdatedDateUTC>
                  <IsSupplier>true</IsSupplier>
                  <IsCustomer>false</IsCustomer>
                </Contact>
                <Contact>
                  <ContactID>1c842b26-90b8-4791-b2d5-a9aea8078aa5</ContactID>
                  <ContactStatus>ACTIVE</ContactStatus>
                  <Name>HMRC</Name>
                  <Addresses>
                    <Address>
                      <AddressType>POBOX</AddressType>
                    </Address>
                    <Address>
                      <AddressType>STREET</AddressType>
                    </Address>
                  </Addresses>
                  <Phones>
                    <Phone>
                      <PhoneType>DDI</PhoneType>
                    </Phone>
                    <Phone>
                      <PhoneType>FAX</PhoneType>
                    </Phone>
                    <Phone>
                      <PhoneType>MOBILE</PhoneType>
                    </Phone>
                    <Phone>
                      <PhoneType>DEFAULT</PhoneType>
                    </Phone>
                  </Phones>
                  <UpdatedDateUTC>2011-04-25T22:10:01.923</UpdatedDateUTC>
                  <IsSupplier>false</IsSupplier>
                  <IsCustomer>false</IsCustomer>
                </Contact>
                <Contact>
                  <ContactID>2dd82f49-e818-4dd0-955b-b637ccaa5597</ContactID>
                  <ContactStatus>ACTIVE</ContactStatus>
                  <Name>City Agency</Name>
                  <Addresses>
                    <Address>
                      <AddressType>POBOX</AddressType>
                      <AddressLine1>P O Box 4321</AddressLine1>
                      <AddressLine2>Central Mailing Centre</AddressLine2>
                      <City>Oaktown</City>
                      <PostalCode>OK12 7TN</PostalCode>
                    </Address>
                    <Address>
                      <AddressType>STREET</AddressType>
                    </Address>
                  </Addresses>
                  <Phones>
                    <Phone>
                      <PhoneType>DDI</PhoneType>
                    </Phone>
                    <Phone>
                      <PhoneType>DEFAULT</PhoneType>
                      <PhoneNumber>9173555</PhoneNumber>
                      <PhoneAreaCode>01</PhoneAreaCode>
                    </Phone>
                    <Phone>
                      <PhoneType>FAX</PhoneType>
                    </Phone>
                    <Phone>
                      <PhoneType>MOBILE</PhoneType>
                    </Phone>
                  </Phones>
                  <UpdatedDateUTC>2011-04-21T04:24:12.44</UpdatedDateUTC>
                  <IsSupplier>false</IsSupplier>
                  <IsCustomer>true</IsCustomer>
                </Contact>
                <Contact>
                  <ContactID>305ca5cf-497d-4fee-a161-cdb30e6be989</ContactID>
                  <ContactStatus>ACTIVE</ContactStatus>
                  <Name>Basket Case</Name>
                  <FirstName>Mary</FirstName>
                  <LastName>Munn</LastName>
                  <EmailAddress>shop@basketcase.co</EmailAddress>
                  <Addresses>
                    <Address>
                      <AddressType>STREET</AddressType>
                    </Address>
                    <Address>
                      <AddressType>POBOX</AddressType>
                      <AddressLine1>Shop 14 Ridgeway Mall</AddressLine1>
                      <AddressLine2>500 River Road</AddressLine2>
                      <City>Pinehaven</City>
                      <PostalCode>PI98 8HV</PostalCode>
                    </Address>
                  </Addresses>
                  <Phones>
                    <Phone>
                      <PhoneType>DDI</PhoneType>
                    </Phone>
                    <Phone>
                      <PhoneType>FAX</PhoneType>
                    </Phone>
                    <Phone>
                      <PhoneType>DEFAULT</PhoneType>
                      <PhoneNumber>9176665</PhoneNumber>
                      <PhoneAreaCode>02</PhoneAreaCode>
                    </Phone>
                    <Phone>
                      <PhoneType>MOBILE</PhoneType>
                      <PhoneNumber>7773001</PhoneNumber>
                      <PhoneAreaCode>01</PhoneAreaCode>
                    </Phone>
                  </Phones>
                  <UpdatedDateUTC>2011-04-22T03:37:20.227</UpdatedDateUTC>
                  <IsSupplier>false</IsSupplier>
                  <IsCustomer>true</IsCustomer>
                </Contact>
                <Contact>
                  <ContactID>2dc0ef7c-582f-4542-963b-dbdc069e4819</ContactID>
                  <ContactStatus>ACTIVE</ContactStatus>
                  <Name>Bayside Wholesale</Name>
                  <Addresses>
                    <Address>
                      <AddressType>STREET</AddressType>
                    </Address>
                    <Address>
                      <AddressType>POBOX</AddressType>
                    </Address>
                  </Addresses>
                  <Phones>
                    <Phone>
                      <PhoneType>DEFAULT</PhoneType>
                      <PhoneNumber>55669</PhoneNumber>
                      <PhoneAreaCode>850</PhoneAreaCode>
                    </Phone>
                    <Phone>
                      <PhoneType>DDI</PhoneType>
                    </Phone>
                    <Phone>
                      <PhoneType>FAX</PhoneType>
                    </Phone>
                    <Phone>
                      <PhoneType>MOBILE</PhoneType>
                    </Phone>
                  </Phones>
                  <UpdatedDateUTC>2011-04-21T20:49:22.373</UpdatedDateUTC>
                  <IsSupplier>true</IsSupplier>
                  <IsCustomer>false</IsCustomer>
                </Contact>
                <Contact>
                  <ContactID>b2c1f980-96c9-45ff-a42b-dca141936c6c</ContactID>
                  <ContactStatus>ACTIVE</ContactStatus>
                  <Name>Rex Media Group</Name>
                  <EmailAddress>info@rexmedia.co</EmailAddress>
                  <Addresses>
                    <Address>
                      <AddressType>STREET</AddressType>
                    </Address>
                    <Address>
                      <AddressType>POBOX</AddressType>
                      <AddressLine1>L9, Nairn Towers</AddressLine1>
                      <AddressLine2>120-130 Flinders Street</AddressLine2>
                      <City>Oaktown</City>
                      <PostalCode>OK12 6TN</PostalCode>
                    </Address>
                  </Addresses>
                  <Phones>
                    <Phone>
                      <PhoneType>MOBILE</PhoneType>
                    </Phone>
                    <Phone>
                      <PhoneType>FAX</PhoneType>
                    </Phone>
                    <Phone>
                      <PhoneType>DDI</PhoneType>
                    </Phone>
                    <Phone>
                      <PhoneType>DEFAULT</PhoneType>
                      <PhoneNumber>4546789</PhoneNumber>
                      <PhoneAreaCode>01</PhoneAreaCode>
                    </Phone>
                  </Phones>
                  <UpdatedDateUTC>2011-04-22T03:06:36.557</UpdatedDateUTC>
                  <IsSupplier>false</IsSupplier>
                  <IsCustomer>true</IsCustomer>
                </Contact>
                <Contact>
                  <ContactID>97cc88ca-f89b-41f0-b8b9-e750b6f2f1d9</ContactID>
                  <ContactStatus>ACTIVE</ContactStatus>
                  <Name>Net Connect</Name>
                  <BankAccountDetails>21-22-23 445566778</BankAccountDetails>
                  <Addresses>
                    <Address>
                      <AddressType>STREET</AddressType>
                    </Address>
                    <Address>
                      <AddressType>POBOX</AddressType>
                      <AddressLine1>P O Box 7900</AddressLine1>
                      <AddressLine2>South Mailing Centre</AddressLine2>
                      <City>Oaktown</City>
                      <PostalCode>OK14 3TN</PostalCode>
                    </Address>
                  </Addresses>
                  <Phones>
                    <Phone>
                      <PhoneType>DEFAULT</PhoneType>
                      <PhoneNumber>500998</PhoneNumber>
                      <PhoneAreaCode>800</PhoneAreaCode>
                    </Phone>
                    <Phone>
                      <PhoneType>FAX</PhoneType>
                      <PhoneNumber>500999</PhoneNumber>
                      <PhoneAreaCode>800</PhoneAreaCode>
                    </Phone>
                    <Phone>
                      <PhoneType>DDI</PhoneType>
                    </Phone>
                    <Phone>
                      <PhoneType>MOBILE</PhoneType>
                    </Phone>
                  </Phones>
                  <UpdatedDateUTC>2011-04-11T02:26:12.64</UpdatedDateUTC>
                  <IsSupplier>true</IsSupplier>
                  <IsCustomer>false</IsCustomer>
                </Contact>
                <Contact>
                  <ContactID>51cbbfb0-8dc9-41aa-aad6-eb93b3cc40c6</ContactID>
                  <ContactStatus>ACTIVE</ContactStatus>
                  <Name>Capital Cab Co</Name>
                  <Addresses>
                    <Address>
                      <AddressType>STREET</AddressType>
                    </Address>
                    <Address>
                      <AddressType>POBOX</AddressType>
                    </Address>
                  </Addresses>
                  <Phones>
                    <Phone>
                      <PhoneType>FAX</PhoneType>
                    </Phone>
                    <Phone>
                      <PhoneType>MOBILE</PhoneType>
                    </Phone>
                    <Phone>
                      <PhoneType>DDI</PhoneType>
                    </Phone>
                    <Phone>
                      <PhoneType>DEFAULT</PhoneType>
                      <PhoneNumber>235689</PhoneNumber>
                      <PhoneAreaCode>800</PhoneAreaCode>
                    </Phone>
                  </Phones>
                  <UpdatedDateUTC>2011-04-21T20:49:22.42</UpdatedDateUTC>
                  <IsSupplier>true</IsSupplier>
                  <IsCustomer>false</IsCustomer>
                </Contact>
                <Contact>
                  <ContactID>be45660b-46fe-412b-9c2e-f667fc5007c3</ContactID>
                  <ContactStatus>ACTIVE</ContactStatus>
                  <Name>Woolworths Market</Name>
                  <Addresses>
                    <Address>
                      <AddressType>POBOX</AddressType>
                    </Address>
                    <Address>
                      <AddressType>STREET</AddressType>
                    </Address>
                  </Addresses>
                  <Phones>
                    <Phone>
                      <PhoneType>DEFAULT</PhoneType>
                    </Phone>
                    <Phone>
                      <PhoneType>DDI</PhoneType>
                    </Phone>
                    <Phone>
                      <PhoneType>MOBILE</PhoneType>
                    </Phone>
                    <Phone>
                      <PhoneType>FAX</PhoneType>
                    </Phone>
                  </Phones>
                  <UpdatedDateUTC>2011-04-11T02:26:12.81</UpdatedDateUTC>
                  <IsSupplier>false</IsSupplier>
                  <IsCustomer>false</IsCustomer>
                </Contact>
                <Contact>
                  <ContactID>94cb6d7b-5291-49f3-a0bc-fc0c01e68575</ContactID>
                  <ContactStatus>ACTIVE</ContactStatus>
                  <Name>Marine Systems</Name>
                  <Addresses>
                    <Address>
                      <AddressType>POBOX</AddressType>
                      <AddressLine1>145 Longdale Way</AddressLine1>
                      <City>Coppertown</City>
                      <PostalCode>CP89 TN8</PostalCode>
                      <AttentionTo>Accounts Dept</AttentionTo>
                    </Address>
                    <Address>
                      <AddressType>STREET</AddressType>
                    </Address>
                  </Addresses>
                  <Phones>
                    <Phone>
                      <PhoneType>MOBILE</PhoneType>
                    </Phone>
                    <Phone>
                      <PhoneType>DEFAULT</PhoneType>
                      <PhoneNumber>9786456</PhoneNumber>
                      <PhoneAreaCode>02</PhoneAreaCode>
                    </Phone>
                    <Phone>
                      <PhoneType>DDI</PhoneType>
                    </Phone>
                    <Phone>
                      <PhoneType>FAX</PhoneType>
                    </Phone>
                  </Phones>
                  <UpdatedDateUTC>2011-04-22T03:37:20.29</UpdatedDateUTC>
                  <IsSupplier>false</IsSupplier>
                  <IsCustomer>true</IsCustomer>
                </Contact>
              </Contacts>
            </Response>
XML;
    }
}
